### ISSUE TITLE
Not working for Blender 2.78a

### ISSUE THREAD

**Issue by OscarOG** [Dummiesman/RipImport#1]
Tested on Blender 2.78a but not working.

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_import_rip\__init__.py", line 93, in execute
    return import_rip.load(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_import_rip\import_rip.py", line 268, in load
    context,
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_import_rip\import_rip.py", line 222, in load_rip
    file = open(filepath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Oscar\\Programas\\qedit\\_NinjaRipper\\2017.02.13_23.37.17_Qedit.exe\\2017.02.13_23.37.48_Qedit.exe\\'

location: <unknown location>:-1

`

**Comment by Dummiesman** [comment]
Working fine here. It seems you tried to load a directory instead of a *.rip file.

**Comment by OscarOG** [comment]
I tried to load a group of *.rip files. Selected all and clicked "import" button. Any ideas?

Edit: Opening one by one is ok, but not working for a group.

**Comment by Dummiesman** [comment]
I've used this for that purpose before: http://blender.stackexchange.com/a/5065

Just adjust the path and replace `bpy.ops.import_scene.obj` with `bpy.ops.import_scene.rip` down at the bottom.

To run it, head into the Scripting view, create a new button, paste/adjust, and click "Run Script".

**Comment by OscarOG** [comment]
Ok this works:

import os
import bpy

# put the location to the folder where the objs are located here in this fashion
# this line will only work on windows ie C:\objects
path_to_rip_dir = os.path.join('C:\\Users\Oscar\\Programas\\qedit\\_NinjaRipper\\2017.02.13_23.37.17_Qedit.exe\\2017.02.13_23.37.48_Qedit.exe')

# get list of all files in directory
file_list = sorted(os.listdir(path_to_rip_dir))

# get a list of files ending in 'obj'
rip_list = [item for item in file_list if item.endswith('.rip')]

# loop through the strings in obj_list and add the files to the scene
for item in rip_list:
    path_to_file = os.path.join(path_to_rip_dir, item)
    bpy.ops.import_scene.rip(filepath = path_to_file)

Isn´t a way to make this easier?

Thanx for the plugin.

**Comment by Dummiesman** [comment]
I could probably at some point make a second import option for multi imports.

**Comment by weituotian** [comment]
@Dummiesman how to import mutil rip file, need helps!!!

**Comment by Dummiesman** [comment]
Importing an entire directory of RIP files is now supported.

**Comment by weituotian** [comment]
@Dummiesman may you make it supported to do that

**Comment by Dummiesman** [comment]
What's the issue ? I use 2.78.
